USE MERCADO_01 
GO

--ALTER TABLE TBL_PRODUTO ALTER COLUMN PROD_COD VARCHAR(15)
--GO

--UPDATE TBL_PRODUTO SET PROD_QTD = 0 WHERE PROD_QTD <= 0


SELECT * FROM TBL_PRODUTO WHERE PROD_COD = ''

INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('OUTROS')
GO

INSERT INTO TBL_PRODUTO(PROD_COD,PROD_NOME,PROD_MARCA,SUB_CAT_ID,PROD_QTD,PROD_QTD_MIN,PROD_VALOR,PROD_VALOR_VENDA)
VALUES('102030405060','Outros',null,9,1,1,0.00,0.00)
