
USE MERCADO_01
INSERT INTO TBL_CLIENTE(CLI_NOME,CLI_DIVIDA) VALUES ('CLIENTE-1',0.00)

--SUB_CATEGORIA
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('INFORMÁTICA')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('MATERIAL ESCOLAR')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('REMÉDIO')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('BJUTERIA')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('CÓSMETICO')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('BRINQUEDOS')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('PAPELÁRIA')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('HIGIENE')
INSERT INTO TBL_SUB_CATEGORIA(SUB_CAT_TIPO) VALUES('OUTROS')



INSERT INTO TBL_FORNECEDOR(FOR_NOME,FOR_CNPJ,FOR_NOME_FANT,FOR_EMAIL,FOR_DESC)
VALUES(NULL,NULL,NULL,NULL,NULL)

INSERT INTO TBL_LOGIN(LOG_LOGIN, LOG_SENHA) VALUES ('master', 'master4555');
INSERT INTO TBL_LOGIN(LOG_LOGIN, LOG_SENHA) VALUES ('master', '130320');

INSERT INTO TBL_PRODUTO(PROD_COD,PROD_NOME,PROD_MARCA,SUB_CAT_ID,PROD_QTD,PROD_QTD_MIN,PROD_VALOR,PROD_VALOR_VENDA)
VALUES('102030405060','Outros',null,9,1,1,0.00,0.00)


