USE MERCADO_01
go

		----> PRODUTOS PREFERIDOS
		CREATE PROCEDURE PROD_MAIS_COMPRADOS
		AS
		SELECT TOP 10 P.PROD_NOME, SUM(ITEM_QTD) AS SAIDAS FROM TBL_ITEM_VENDA AS IV
		INNER JOIN TBL_PRODUTO AS P ON P.PROD_ID = IV.PROD_ID
		GROUP BY P.PROD_NOME
		ORDER BY SAIDAS DESC
	    GO

		
	
		-----> PRODUTOS MENOS VENDIDOS
		CREATE PROCEDURE PROD_MENOS_VENDIDOS
		AS
		SELECT TOP 10 P.PROD_NOME, SUM(ITEM_QTD) AS SAIDAS FROM TBL_ITEM_VENDA AS IV
		INNER JOIN TBL_PRODUTO AS P ON P.PROD_ID = IV.PROD_ID
		GROUP BY P.PROD_NOME
		ORDER BY SAIDAS 
		GO



	CREATE PROCEDURE DIVIDA
	AS
		SELECT SUM(CLI_DIVIDA) AS VALOR FROM TBL_CLIENTE
	GO