USE MERCADO_01

SELECT * FROM TBL_PRODUTO
SELECT * FROM TBL_FECHAMENTO
SELECT * FROM TBL_PROD_FORN
SELECT * FROM TBL_VENDA
SELECT * FROM TBL_ITEM_VENDA
SELECT * FROM TBL_PROD_FORN
SELECT * FROM TBL_SUB_CATEGORIA
SELECT * FROM TBL_LOGIN
SELECT * FROM TBL_FOTO
SELECT * FROM TBL_FORNECEDOR
SELECT * FROM TBL_ENDERECO
SELECT * FROM TBL_TELEFONE
SELECT * FROM TBL_FOR_END
SELECT * FROM TBL_CLIENTE ORDER BY CLI_NOME ASC

SELECT * FROM TBL_CLIENTE where CLI_DIVIDA < 0.00 and CLI_ID > 1

SELECT V.VEN_ID, V.VEN_PAGAMENTO,V.VEN_PARCELA, P.PROD_NOME, IV.ITEM_QTD, IV.ITEM_VALOR, V.VEN_TOTAL, CONVERT(VARCHAR(10),V.VEN_DATE, 103) AS DATA FROM TBL_ITEM_VENDA AS IV
INNER JOIN TBL_PRODUTO AS P ON P.PROD_ID = IV.PROD_ID
INNER JOIN TBL_VENDA AS V ON V.VEN_ID = IV.VEN_ID WHERE V.VEN_ID = (SELECT MAX(VEN_ID) FROM TBL_VENDA)


SELECT FECH_CREDIARIO, FECH_CREDITO, FECH_DEBITO, FECH_DINHEIRO , CONVERT(VARCHAR(10),FECH_DATA, 103) AS DATA, CONVERT(VARCHAR(8),FECH_HORA, 108) AS HORA,
FECH_TOTAL FROM TBL_FECHAMENTO where FECH_ID = (select max(FECH_ID) from TBL_FECHAMENTO)

















INSERT INTO TBL_FECHAMENTO (FECH_DEBITO, FECH_CREDITO, FECH_DINHEIRO, FECH_CREDIARIO, FECH_TOTAL, FECH_HORA ,FECH_DATA)
VALUES (@DEBITO,@CREDITO,@DINHEIRO, @CREDIARIO, @TOTAL,@HORA, @DATA) 

SELECT FECH_DEBITO, FECH_CREDITO, FECH_CREDIARIO, FECH_DINHEIRO, FECH_DATA, FECH_HORA, FECH_TOTAL FROM TBL_FECHAMENTO

select sum(VEN_TOTAL) as Valor from TBL_VENDA where VEN_PAGAMENTO = 'Crediário' AND VEN_DATE = '2020-03-09'

select sum(VEN_TOTAL) as Débito from TBL_VENDA where VEN_PAGAMENTO = 'Débito' AND VEN_DATE = '2020-03-03'

select sum(VEN_TOTAL) as Crédito from TBL_VENDA where VEN_PAGAMENTO = 'Crédito' AND VEN_DATE = '2020-03-03'

select sum(VEN_TOTAL) as Total from TBL_VENDA

SELECT V.VEN_DATE, V.VEN_PAGAMENTO, V.VEN_PARCELA, V.VEN_TOTAL, V.VEN_ID, C.CLI_NOME FROM TBL_VENDA AS V INNER JOIN TBL_CLIENTE AS C ON C.CLI_ID = V.CLI_ID WHERE VEN_DATE = '2020-03-03'

UPDATE TBL_CLIENTE SET CLI_DIVIDA -= 80.00 WHERE CLI_ID = 2